#!/bin/bash

set -e

tmpfile=`mktemp /tmp/tempfile.XXXXXXXXX`
cp `rospack find utexas_guidance_ros`/perspectives/segbot.perspective $tmpfile
if [ "$1" == "ns" ]
then
  # A robot name has been specified. Simply replace the keyword segbot with supplied robot name.
  sed -i "s/segbot/$2/g" $tmpfile
else
  # No robot name specified, run everything in top level namespace.
  sed -i "s/\/segbot//g" $tmpfile
  sed -i "s/segbot\///g" $tmpfile
  sed -i "s/segbot//g" $tmpfile
fi
rosrun rqt_gui rqt_gui --perspective-file $tmpfile _font_size:=20
rm -f $tmpfile
